"""create employees table

Revision ID: 07be32e9faa2
Revises: 50dd8bb92627
Create Date: 2024-10-08 20:51:08.533544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07be32e9faa2'
down_revision = '50dd8bb92627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('start_schedule', sa.String(length=128), nullable=False),
    sa.Column('end_schedule', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
