"""edit enclosures table

Revision ID: 270a7d2c3987
Revises: 07be32e9faa2
Create Date: 2024-10-09 22:19:32.547203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '270a7d2c3987'
down_revision = '07be32e9faa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedings', schema=None) as batch_op:
        batch_op.alter_column('feeding_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('reminder',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedings', schema=None) as batch_op:
        batch_op.alter_column('reminder',
               existing_type=sa.String(length=128),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('feeding_time',
               existing_type=sa.String(length=128),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
