"""edit visitor table

Revision ID: 5b3814f7ebec
Revises: eb01f07b90b5
Create Date: 2024-10-10 09:55:38.852345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3814f7ebec'
down_revision = 'eb01f07b90b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_column('fixed_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_price', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
