"""create animal table

Revision ID: 92b497f1ad58
Revises: e0e287cd5927
Create Date: 2024-10-08 15:43:19.042128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b497f1ad58'
down_revision = 'e0e287cd5927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('special_req', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('special_req')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('species')

    # ### end Alembic commands ###
